# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
future: true

excerpt_separator: <!--excerpt_separator-->

# Setup
title:            A journey into Valhalla
url:              http://valhalla-game.com/
baseurl:          /