# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Exclude
exclude:          ["example"]

# Setup
title:            A Journey in Valhalla
tagline:          Instance focused MORPG
description:      "A blog about an indie game in production."
url:              http://valhalla-game.se
baseurl:          /

paginate:         5
