# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Exclude
exclude:          ["example"]

# Setup
title:            A journey into Valhalla
url:              http://valhalla-game.com
baseurl:          /

paginate:         5
