# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
future: true

excerpt_separator: <!--excerpt_separator-->

# Setup
title:            A journey through Valhalla
url:              http://valhalla-game.com/
baseurl:          /
